### ISSUE TITLE
Использование проверки кода в VSCode

### ISSUE THREAD

**Issue by germanFid** [germanFid/FieldAveraging#22]
Для проверки кода используются такие программы, как линтеры. Линтеры автоматически находят ошибки в оформлении и не только. Мы будем использовать линтер **Pylama**, потому что он легковесный и выполняет нужную нам задачу: форматирование кода и недопущение ошибок.

### Установка линтера

Для начала, у вас должен быть установлен плагин [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)

> _Подсказка: в строке команд необязательно вводить команду целиком, можно лишь начать ее писать, а затем, в открывшемся списке выбрать нужную команду_

1. Нажимаем **Ctrl + Shift + P** (откроется строка команд) и вводим `Python : Enable/Disable Linting`, выбираем _"Enable"_
2. Снова открываем строку команд и вводим `Python : Select Linter`, выбираем `Pylama` из предложенных вариантов.
3. VSCode предложит установить линтер, соглашаемся
4. Готово! Линтер должен заработать сразу после установки

**Comment by Nickonson** [comment]
Все написал, а как пользоваться линтером не написал 🥇

**Comment by Lukedam** [comment]
Не ну я считаю интеллектом и умом

**Comment by Lukedam** [comment]
такой штуки кстати нет 'Python : Enable/Disable Linting'
