### ISSUE TITLE
Распараллеливание функции осреднения, конкретно basic_2d_array_averaging и basic_3d_array_averaging

### ISSUE THREAD

**Issue by Lukedam** [germanFid/FieldAveraging#23]
Любыми методами ввести распараллеливание квадрата и куба

**Comment by germanFid** [comment]
@Lukedam Будет сделано)

**Comment by germanFid** [comment]
`basic_2d_array_averaging` успешно распаралелена

**Comment by Lukedam** [comment]
@germanFid Прошу предоставить тестовый расчет программой для матрицы 3x5 c 15 в разных местах матрицы в левом верхнем углу, чтобы убедитсья что она осредняет правильно, предоставить график температур.

**Comment by Lukedam** [comment]
Все сделано неделю назад, смысла держать это не вижу
