### ISSUE TITLE
Ввод-вывод в .plt

### ISSUE THREAD

**Issue by germanFid** [germanFid/FieldAveraging#3]
По сути, тут тот же самый .csv, только нужно пропустить несколько строк и можно читать как таблицу с разделителем `,`

@Lukedam Если есть какие-то дополнительные пожелания к фиче, прошу в комментарии

**Comment by germanFid** [comment]
Вообще в современных языках программирования это делается вот [так](https://stackoverflow.com/questions/32859246/how-to-convert-plt-file-to-csv-file-and-also-attributes-are-missing)

**Comment by Lukedam** [comment]
Да, хорошо, можешь ли ты это запрогать как функции для фортрана, которая будет сначала получать файл, а потом сохранять?
