### ISSUE TITLE
Исследование алгоритма

### ISSUE THREAD

**Issue by Svetlana1147** [germanFid/FieldAveraging#7]
файл отчета отошёл на 5 минут...

**Comment by Svetlana1147** [comment]
[Отчёт по исследованию алгоритма.docx](https://github.com/germanFid/FieldAveraging/files/10748001/default.docx)

**Comment by Svetlana1147** [comment]
В выводе надо написать, что алгоритм надо оптимизировать

**Comment by Webroyde** [comment]
[Отчет по исследованию алгоритма осреднения.docx](https://github.com/germanFid/FieldAveraging/files/10748378/default.docx)

**Comment by Webroyde** [comment]
[Отчет по исследованию алгоритма осреднения.docx](https://github.com/germanFid/FieldAveraging/files/10748404/default.docx)

**Comment by Webroyde** [comment]
Не стыдно так наебывать?
